// Adapt the embedded renderer to native online movement atlases.
// Bounded function replacements preserve classic VIP artwork and standalone HTML.
'use strict';
const replacements = [
  [
    "const MAIN_HERO_DIRECTIONS = ['s', 'se', 'e', 'ne', 'n', 'nw', 'w', 'sw'];\nconst MAIN_HERO_WALK_FRAMES = { male: 6, female: 6 };\nconst MAIN_HERO_SPRITE = {\n  w: 48, h: 48, scale: 1.25,\n  // Caixa junto dos pés; mantém aproximadamente a colisão anterior no mundo.\n  body: { w: 16, h: 12, ox: 16, oy: 35 }\n};\n\n",
    "const MAIN_HERO_DIRECTIONS = ['s', 'se', 'e', 'ne', 'n', 'nw', 'w', 'sw'];\nconst MAIN_HERO_WALK_FRAMES = { male: 6, female: 6 };\nconst MAIN_HERO_FRAME_MS = 200;\nconst MAIN_HERO_SPRITE = {\n  w: 64, h: 64, scale: 0.9375,\n  // Caixa junto dos pés; mantém aproximadamente a colisão anterior no mundo.\n  body: { w: 64 / 3, h: 16, ox: 64 / 3, oy: 140 / 3 }\n};\n\n"
  ],
  [
    "function createPlayableHeroTextures(scene, atlasKey, prefix, walkFrames) {\n  const texture = scene.textures.get(atlasKey);\n  if (!texture || texture.key === '__MISSING') throw new Error('Atlas do personagem não carregado');\n  setTextureSampling242(scene, atlasKey, 'pixel');\n  const image = texture.getSourceImage();\n  MAIN_HERO_DIRECTIONS.forEach((direction, column) => {\n    for (let frame = 0; frame <= walkFrames; frame++) {\n      const key = prefix + direction + '_' + frame;\n      // As laterais femininas (leste/oeste) vêm de um sheet dedicado.\n      // Se gerarmos essas direções também a partir do atlas original,\n      // o cabelo duplicado volta a aparecer.\n      if (prefix === 'femaleHero_' && (direction === 'e' || direction === 'w')) continue;\n      if (scene.textures.exists(key)) continue;\n      // Cada pose precisa ser uma textura independente. O atlas tem frames\n      // encostados; desenhar diretamente dele pode deixar pixels do frame\n      // anterior visíveis durante a troca lateral (principalmente no cabelo).\n      const canvas = document.createElement('canvas');\n      canvas.width = MAIN_HERO_SPRITE.w;\n      canvas.height = MAIN_HERO_SPRITE.h;\n      const ctx = canvas.getContext('2d', { alpha: true });\n      ctx.imageSmoothingEnabled = false;\n      ctx.clearRect(0, 0, canvas.width, canvas.height);\n      ctx.save();\n      ctx.beginPath();\n      ctx.rect(0, 0, canvas.width, canvas.height);\n      ctx.clip();\n      ctx.drawImage(\n        image,\n        Math.floor(column * MAIN_HERO_SPRITE.w),\n        Math.floor(frame * MAIN_HERO_SPRITE.h),\n        MAIN_HERO_SPRITE.w,\n        MAIN_HERO_SPRITE.h,\n        0, 0,\n        MAIN_HERO_SPRITE.w,\n        MAIN_HERO_SPRITE.h\n      );\n      ctx.restore();\n      // A textura antiga já foi removida acima, antes do novo recorte.\n      scene.textures.addCanvas(key, canvas);\n      setTextureSampling242(scene, key, 'pixel');\n    }\n  });\n}\n\n",
    "function createPlayableHeroTextures(scene, atlasKey, prefix, walkFrames) {\n  const texture = scene.textures.get(atlasKey);\n  if (!texture || texture.key === '__MISSING') throw new Error('Atlas do personagem não carregado');\n  setTextureSampling242(scene, atlasKey, 'pixel');\n  const image = texture.getSourceImage();\n  const sourceCell = image.width / MAIN_HERO_DIRECTIONS.length;\n  if (![48, 64].includes(sourceCell) || image.height !== sourceCell * (walkFrames + 1)) {\n    throw new Error('Dimensões inválidas do atlas do personagem');\n  }\n  MAIN_HERO_DIRECTIONS.forEach((direction, column) => {\n    for (let frame = 0; frame <= walkFrames; frame++) {\n      const key = prefix + direction + '_' + frame;\n      // As laterais femininas (leste/oeste) vêm de um sheet dedicado.\n      // Se gerarmos essas direções também a partir do atlas original,\n      // o cabelo duplicado volta a aparecer.\n      if (prefix === 'femaleHero_' && (direction === 'e' || direction === 'w')) continue;\n      if (scene.textures.exists(key)) continue;\n      // Cada pose precisa ser uma textura independente. O atlas tem frames\n      // encostados; desenhar diretamente dele pode deixar pixels do frame\n      // anterior visíveis durante a troca lateral (principalmente no cabelo).\n      const canvas = document.createElement('canvas');\n      canvas.width = MAIN_HERO_SPRITE.w;\n      canvas.height = MAIN_HERO_SPRITE.h;\n      const ctx = canvas.getContext('2d', { alpha: true });\n      ctx.imageSmoothingEnabled = false;\n      ctx.clearRect(0, 0, canvas.width, canvas.height);\n      ctx.save();\n      ctx.beginPath();\n      ctx.rect(0, 0, canvas.width, canvas.height);\n      ctx.clip();\n      ctx.drawImage(\n        image,\n        column * sourceCell,\n        frame * sourceCell,\n        sourceCell,\n        sourceCell,\n        0, 0,\n        MAIN_HERO_SPRITE.w,\n        MAIN_HERO_SPRITE.h\n      );\n      ctx.restore();\n      // A textura antiga já foi removida acima, antes do novo recorte.\n      scene.textures.addCanvas(key, canvas);\n      setTextureSampling242(scene, key, 'pixel');\n    }\n  });\n}\n\n"
  ],
  [
    "function createFemaleSideTextures(scene) {\n  if (window.__femaleSideTexturesReady) return Promise.resolve();\n\n  const sheets = [\n    ['e', FEMALE_EAST_SHEET_DATA],\n    ['w', FEMALE_WEST_SHEET_DATA]\n  ];\n\n  return Promise.all(sheets.map(([direction, data]) => new Promise((resolve) => {\n    const image = new Image();\n    image.onload = () => {\n      const sourceFrameMap = [0, 1, 2, 3, 4, 5, 4];\n      for (let frame = 0; frame <= 6; frame++) {\n        const key = 'femaleHero_' + direction + '_' + frame;\n        const sourceFrame = sourceFrameMap[frame] ?? 0;\n\n        // Aqui já estamos no boot, antes de criar o personagem. Então é seguro\n        // sobrescrever as texturas leste/oeste femininas com o sheet novo.\n        if (scene.textures.exists(key)) scene.textures.remove(key);\n\n        const canvas = document.createElement('canvas');\n        canvas.width = 48;\n        canvas.height = 48;\n        const ctx = canvas.getContext('2d');\n        ctx.imageSmoothingEnabled = false;\n        ctx.clearRect(0, 0, 48, 48);\n\n        // O sheet enviado tem 6 quadros 64x64. O jogo precisa de 7 chaves:\n        // 0 = idle, 1..6 = caminhada. Usamos um mapeamento fechado para evitar\n        // quadro vazio e manter o ciclo lateral suave.\n        ctx.drawImage(image, sourceFrame * 64, 0, 64, 64, 0, 0, 48, 48);\n        scene.textures.addCanvas(key, canvas);\n      setTextureSampling242(scene, key, 'pixel');\n      }\n      resolve();\n    };\n    image.onerror = resolve;\n    image.src = data;\n  })) ).then(() => {\n    window.__femaleSideTexturesReady = true;\n  });\n}\n\n",
    "function createFemaleSideTextures(scene) {\n  if (window.__femaleSideTexturesReady) return Promise.resolve();\n\n  const sheets = [\n    ['e', FEMALE_EAST_SHEET_DATA],\n    ['w', FEMALE_WEST_SHEET_DATA]\n  ];\n\n  return Promise.all(sheets.map(([direction, data]) => new Promise((resolve) => {\n    const image = new Image();\n    image.onload = () => {\n      const sourceFrameMap = [0, 1, 2, 3, 4, 5, 4];\n      for (let frame = 0; frame <= 6; frame++) {\n        const key = 'femaleHero_' + direction + '_' + frame;\n        const sourceFrame = sourceFrameMap[frame] ?? 0;\n\n        // Aqui já estamos no boot, antes de criar o personagem. Então é seguro\n        // sobrescrever as texturas leste/oeste femininas com o sheet novo.\n        if (scene.textures.exists(key)) scene.textures.remove(key);\n\n        const canvas = document.createElement('canvas');\n        canvas.width = MAIN_HERO_SPRITE.w;\n        canvas.height = MAIN_HERO_SPRITE.h;\n        const ctx = canvas.getContext('2d');\n        ctx.imageSmoothingEnabled = false;\n        ctx.clearRect(0, 0, canvas.width, canvas.height);\n\n        // O sheet enviado tem 6 quadros 64x64. O jogo precisa de 7 chaves:\n        // 0 = idle, 1..6 = caminhada. Usamos um mapeamento fechado para evitar\n        // quadro vazio e manter o ciclo lateral suave.\n        ctx.drawImage(image, sourceFrame * 64, 0, 64, 64, 0, 0, canvas.width, canvas.height);\n        scene.textures.addCanvas(key, canvas);\n      setTextureSampling242(scene, key, 'pixel');\n      }\n      resolve();\n    };\n    image.onerror = resolve;\n    image.src = data;\n  })) ).then(() => {\n    window.__femaleSideTexturesReady = true;\n  });\n}\n\n"
  ],
  [
    "function setMainHeroPose(sprite, state, direction, frameField, timerField, moving, delta) {\n  const count = GameState.player.avatar === 'female' ? MAIN_HERO_WALK_FRAMES.female : MAIN_HERO_WALK_FRAMES.male;\n  if (moving) {\n    if (!state[frameField] || state[frameField] > count) state[frameField] = 1;\n    state[timerField] += delta;\n    const steps = Math.floor(state[timerField] / 200);\n    if (steps) {\n      state[timerField] %= 200;\n      state[frameField] = ((state[frameField] - 1 + steps) % count) + 1;\n    }\n  } else { state[frameField] = 0; state[timerField] = 0; }\n  const key = playableHeroKey(direction, state[frameField]);\n  // Evita desaparecer enquanto os sprites laterais femininos ainda carregam\n  // (o carregamento dos GIFs é assíncrono).\n  if (!sprite.scene.textures.exists(key)) return;\n  if (sprite.texture.key !== key) sprite.setTexture(key);\n}\n\n",
    "function setMainHeroPose(sprite, state, direction, frameField, timerField, moving, delta) {\n  const count = GameState.player.avatar === 'female' ? MAIN_HERO_WALK_FRAMES.female : MAIN_HERO_WALK_FRAMES.male;\n  if (moving) {\n    if (!state[frameField] || state[frameField] > count) state[frameField] = 1;\n    state[timerField] = (Number.isFinite(state[timerField]) ? state[timerField] : 0) +\n      (Number.isFinite(delta) ? Math.max(0, delta) : 0);\n    const steps = Math.floor(state[timerField] / MAIN_HERO_FRAME_MS);\n    if (steps) {\n      state[timerField] %= MAIN_HERO_FRAME_MS;\n      state[frameField] = ((state[frameField] - 1 + steps) % count) + 1;\n    }\n  } else { state[frameField] = 0; state[timerField] = 0; }\n  const key = playableHeroKey(direction, state[frameField]);\n  // Evita desaparecer enquanto os sprites laterais femininos ainda carregam\n  // (o carregamento dos GIFs é assíncrono).\n  if (!sprite.scene.textures.exists(key)) return;\n  if (sprite.texture.key !== key) sprite.setTexture(key);\n}\n\n"
  ],
  [
    "function gcSyncSprites() {\n  const s = getActiveGameScene(); if (!s || !s.add || typeof GameState === 'undefined' || !GameState.player) return;\n  const myMap = mapaAtual154();\n  if (gcSpriteMapa154 !== myMap) { // v154 — trocou de mapa: limpa quem era do mapa antigo\n    for (const k in gcPlEls) { try { gcPlEls[k].sp.destroy(); gcPlEls[k].txt.destroy(); } catch (e) {} }\n    gcPlEls = {}; gcSpriteMapa154 = myMap;\n  }\n  const alive = {};\n  for (const r of gcRoster) {\n    if (r.me || r.map !== myMap) continue;\n    alive[r.nick] = 1;\n    let o = gcPlEls[r.nick];\n    if (!o || !o.sp || !o.sp.scene || gcSpriteScene !== s) {\n      if (o) { try { o.sp.destroy(); o.txt.destroy(); } catch (e) {} }\n      const fem = r.sex === 'f';\n      const tex = fem ? 'femaleHero_s_0' : 'githubMale_s_0';\n      if (!game.textures.exists(tex)) continue;\n      // Outros jogadores seguem o tamanho do personagem local em cada mapa.\n      const scale = (s.player && s.player.scaleX) || MAIN_HERO_SPRITE.scale;\n      const sp = s.add.sprite(r.x, r.y, tex).setDepth(7).setScale(scale);\n      const txt = s.add.text(r.x, r.y - 46 * scale, r.nick, { fontFamily: 'monospace', fontSize: '10px', color: '#7ef0ff', stroke: '#000000', strokeThickness: 3 }).setOrigin(0.5, 1).setDepth(9);\n      o = gcPlEls[r.nick] = { sp: sp, txt: txt, tx: r.x, ty: r.y, dir: 's', f: 0, ft: 0, samp: [{ x: r.x, y: r.y, t: Date.now() }] }; // v172 — 1ª amostra\n    }\n    const remoteBase = r.sex === 'f' ? 'femaleHero_' : 'githubMale_';\n    if (o.base !== remoteBase) {\n      o.base = remoteBase; o.walkFrames = r.sex === 'f' ? MAIN_HERO_WALK_FRAMES.female : MAIN_HERO_WALK_FRAMES.male;\n      o.f = 0; o.ft = 0; o.sp.setTexture(remoteBase + 's_0');\n    }\n    o.tx = r.x; o.ty = r.y;\n    const t172 = Date.now(); // v172 — amostra p/ predição (+ snap em teleporte)\n    o.samp = o.samp || [];\n    const ps172 = o.samp[o.samp.length - 1];\n    if (!ps172 || ps172.x !== r.x || ps172.y !== r.y || t172 - ps172.t > 900) {\n      o.samp.push({ x: r.x, y: r.y, t: t172 });\n      if (o.samp.length > 3) o.samp.shift();\n    }\n    if (o.sp && Math.abs(r.x - o.sp.x) + Math.abs(r.y - o.sp.y) > 1100) {\n      o.sp.x = r.x; o.sp.y = r.y; // teleporte real: gruda, não desliza o mapa todo\n      o.samp = [{ x: r.x, y: r.y, t: t172 }];\n    }\n  }\n  for (const k in gcPlEls) if (!alive[k]) { try { gcPlEls[k].sp.destroy(); gcPlEls[k].txt.destroy(); } catch (e) {} delete gcPlEls[k]; }\n  gcSpriteScene = s;\n}\n",
    "function gcSyncSprites() {\n  const s = getActiveGameScene(); if (!s || !s.add || typeof GameState === 'undefined' || !GameState.player) return;\n  const myMap = mapaAtual154();\n  if (gcSpriteMapa154 !== myMap) { // v154 — trocou de mapa: limpa quem era do mapa antigo\n    for (const k in gcPlEls) { try { gcPlEls[k].sp.destroy(); gcPlEls[k].txt.destroy(); } catch (e) {} }\n    gcPlEls = {}; gcSpriteMapa154 = myMap;\n  }\n  const alive = {};\n  for (const r of gcRoster) {\n    if (r.me || r.map !== myMap) continue;\n    alive[r.nick] = 1;\n    let o = gcPlEls[r.nick];\n    if (!o || !o.sp || !o.sp.scene || gcSpriteScene !== s) {\n      if (o) { try { o.sp.destroy(); o.txt.destroy(); } catch (e) {} }\n      const fem = r.sex === 'f';\n      const tex = fem ? 'femaleHero_s_0' : 'githubMale_s_0';\n      if (!game.textures.exists(tex)) continue;\n      // Outros jogadores seguem o tamanho do personagem local em cada mapa.\n      const scale = (s.player && s.player.scaleX) || MAIN_HERO_SPRITE.scale;\n      const sp = s.add.sprite(r.x, r.y, tex).setDepth(7).setScale(scale);\n      const txt = s.add.text(r.x, r.y - MAIN_HERO_SPRITE.h * scale * 0.75, r.nick, { fontFamily: 'monospace', fontSize: '10px', color: '#7ef0ff', stroke: '#000000', strokeThickness: 3 }).setOrigin(0.5, 1).setDepth(9);\n      o = gcPlEls[r.nick] = { sp: sp, txt: txt, tx: r.x, ty: r.y, dir: 's', f: 0, ft: 0, samp: [{ x: r.x, y: r.y, t: Date.now() }] }; // v172 — 1ª amostra\n    }\n    const remoteBase = r.sex === 'f' ? 'femaleHero_' : 'githubMale_';\n    if (o.base !== remoteBase) {\n      o.base = remoteBase; o.walkFrames = r.sex === 'f' ? MAIN_HERO_WALK_FRAMES.female : MAIN_HERO_WALK_FRAMES.male;\n      o.f = 0; o.ft = 0; o.sp.setTexture(remoteBase + 's_0');\n    }\n    o.tx = r.x; o.ty = r.y;\n    const t172 = Date.now(); // v172 — amostra p/ predição (+ snap em teleporte)\n    o.samp = o.samp || [];\n    const ps172 = o.samp[o.samp.length - 1];\n    if (!ps172 || ps172.x !== r.x || ps172.y !== r.y || t172 - ps172.t > 900) {\n      o.samp.push({ x: r.x, y: r.y, t: t172 });\n      if (o.samp.length > 3) o.samp.shift();\n    }\n    if (o.sp && Math.abs(r.x - o.sp.x) + Math.abs(r.y - o.sp.y) > 1100) {\n      o.sp.x = r.x; o.sp.y = r.y; // teleporte real: gruda, não desliza o mapa todo\n      o.samp = [{ x: r.x, y: r.y, t: t172 }];\n    }\n  }\n  for (const k in gcPlEls) if (!alive[k]) { try { gcPlEls[k].sp.destroy(); gcPlEls[k].txt.destroy(); } catch (e) {} delete gcPlEls[k]; }\n  gcSpriteScene = s;\n}\n"
  ],
  [
    "function renderCharacterChoice(kind) {\n  const skin = characterSkin(kind);\n  draftCharacterChoice = skin.kind;\n  const preview = document.getElementById('char-preview-canvas');\n  const texture = game.textures.get(skin.key()).getSourceImage();\n  if (preview && texture) {\n    const ctx = preview.getContext('2d');\n    ctx.imageSmoothingEnabled = false;\n    ctx.clearRect(0, 0, preview.width, preview.height);\n    ctx.drawImage(texture, 0, 0, 48, 48, 0, 0, preview.width, preview.height);\n  }\n  const title = document.getElementById('char-preview-name');\n  const status = document.getElementById('char-preview-status');\n  if (title) title.textContent = skin.label;\n  if (status) status.textContent = skin.kind === GameState.player.avatar ? 'Skin atual' : 'Pronta para selecionar';\n  AVAILABLE_CHARACTER_SKINS.forEach(option => {\n    const button = document.getElementById(option.id);\n    if (!button) return;\n    const optionTexture = game.textures.get(option.key()).getSourceImage();\n    const canvas = button.querySelector('canvas');\n    const ctx = canvas.getContext('2d');\n    ctx.imageSmoothingEnabled = false;\n    ctx.clearRect(0, 0, 48, 48);\n    ctx.drawImage(optionTexture, 0, 0, 48, 48, 0, 0, 48, 48);\n    const selected = draftCharacterChoice === option.kind;\n    button.classList.toggle('is-selected', selected);\n    button.setAttribute('aria-pressed', selected ? 'true' : 'false');\n    button.querySelector('small').textContent = selected ? (option.kind === GameState.player.avatar ? 'Skin atual' : 'Selecionada') : 'Selecionar skin';\n  });\n  const index = AVAILABLE_CHARACTER_SKINS.findIndex(option => option.kind === skin.kind);\n  const prev = document.getElementById('char-prev');\n  const next = document.getElementById('char-next');\n  if (prev) prev.disabled = index <= 0;\n  if (next) next.disabled = index >= AVAILABLE_CHARACTER_SKINS.length - 1;\n}\n",
    "function renderCharacterChoice(kind) {\n  const skin = characterSkin(kind);\n  draftCharacterChoice = skin.kind;\n  const preview = document.getElementById('char-preview-canvas');\n  const texture = game.textures.get(skin.key()).getSourceImage();\n  if (preview && texture) {\n    const ctx = preview.getContext('2d');\n    ctx.imageSmoothingEnabled = false;\n    ctx.clearRect(0, 0, preview.width, preview.height);\n    const cell = texture.width / MAIN_HERO_DIRECTIONS.length;\n    ctx.drawImage(texture, 0, 0, cell, cell, 0, 0, preview.width, preview.height);\n  }\n  const title = document.getElementById('char-preview-name');\n  const status = document.getElementById('char-preview-status');\n  if (title) title.textContent = skin.label;\n  if (status) status.textContent = skin.kind === GameState.player.avatar ? 'Skin atual' : 'Pronta para selecionar';\n  AVAILABLE_CHARACTER_SKINS.forEach(option => {\n    const button = document.getElementById(option.id);\n    if (!button) return;\n    const optionTexture = game.textures.get(option.key()).getSourceImage();\n    const canvas = button.querySelector('canvas');\n    const ctx = canvas.getContext('2d');\n    ctx.imageSmoothingEnabled = false;\n    ctx.clearRect(0, 0, 48, 48);\n    const cell = optionTexture.width / MAIN_HERO_DIRECTIONS.length;\n    ctx.drawImage(optionTexture, 0, 0, cell, cell, 0, 0, canvas.width, canvas.height);\n    const selected = draftCharacterChoice === option.kind;\n    button.classList.toggle('is-selected', selected);\n    button.setAttribute('aria-pressed', selected ? 'true' : 'false');\n    button.querySelector('small').textContent = selected ? (option.kind === GameState.player.avatar ? 'Skin atual' : 'Selecionada') : 'Selecionar skin';\n  });\n  const index = AVAILABLE_CHARACTER_SKINS.findIndex(option => option.kind === skin.kind);\n  const prev = document.getElementById('char-prev');\n  const next = document.getElementById('char-next');\n  if (prev) prev.disabled = index <= 0;\n  if (next) next.disabled = index >= AVAILABLE_CHARACTER_SKINS.length - 1;\n}\n"
  ],
  [
    "function getHeroAvatarURL() {\n  try {\n    const gameCanvas = document.createElement('canvas');\n    gameCanvas.width = 48; gameCanvas.height = 48;\n    const ctx = gameCanvas.getContext('2d');\n    ctx.imageSmoothingEnabled = false;\n    const atlas = game.textures.get(GameState.player.avatar === 'female' ? FEMALE_HERO_ATLAS_KEY : MAIN_HERO_ATLAS_KEY).getSourceImage();\n    ctx.drawImage(atlas, 8, 0, 32, 32, 0, 0, 48, 48);\n    return gameCanvas.toDataURL();\n  } catch (e) { return null; }\n}\n\n",
    "function getHeroAvatarURL() {\n  try {\n    const gameCanvas = document.createElement('canvas');\n    gameCanvas.width = 48; gameCanvas.height = 48;\n    const ctx = gameCanvas.getContext('2d');\n    ctx.imageSmoothingEnabled = false;\n    const atlas = game.textures.get(GameState.player.avatar === 'female' ? FEMALE_HERO_ATLAS_KEY : MAIN_HERO_ATLAS_KEY).getSourceImage();\n    const cell = atlas.width / MAIN_HERO_DIRECTIONS.length;\n    ctx.drawImage(atlas, cell / 6, 0, cell * 2 / 3, cell * 2 / 3, 0, 0, 48, 48);\n    return gameCanvas.toDataURL();\n  } catch (e) { return null; }\n}\n\n"
  ],
  [
    "  function hero240(){\n    const p=GameState.player,kind=p.avatar==='female'?'female':'male';let sprite=null;\n    try{\n      const cv=document.createElement('canvas');cv.width=48;cv.height=48;const ctx=cv.getContext('2d');ctx.imageSmoothingEnabled=false;\n      const prefix=kind==='female'?'femaleHero_':'githubMale_',texture=game.textures.get(prefix+'s_0');\n      if(texture&&texture.key!=='__MISSING')ctx.drawImage(texture.getSourceImage(),0,0,48,48);\n      else ctx.drawImage(game.textures.get(kind==='female'?FEMALE_HERO_ATLAS_KEY:MAIN_HERO_ATLAS_KEY).getSourceImage(),0,0,48,48,0,0,48,48);\n      sprite=cv.toDataURL('image/png');\n    }catch(e){sprite=typeof getHeroAvatarURL==='function'?getHeroAvatarURL():null;}\n    return {kind,sprite,name:window.CHAOS_ONLINE?.nick||'Você',level:p.lvl||1};\n  }\n",
    "  function hero240(){\n    const p=GameState.player,kind=p.avatar==='female'?'female':'male';let sprite=null;\n    try{\n      const cv=document.createElement('canvas');cv.width=48;cv.height=48;const ctx=cv.getContext('2d');ctx.imageSmoothingEnabled=false;\n      const prefix=kind==='female'?'femaleHero_':'githubMale_',texture=game.textures.get(prefix+'s_0');\n      if(texture&&texture.key!=='__MISSING')ctx.drawImage(texture.getSourceImage(),0,0,48,48);\n      else { const atlas=game.textures.get(kind==='female'?FEMALE_HERO_ATLAS_KEY:MAIN_HERO_ATLAS_KEY).getSourceImage(),cell=atlas.width/8;ctx.drawImage(atlas,0,0,cell,cell,0,0,48,48); }\n      sprite=cv.toDataURL('image/png');\n    }catch(e){sprite=typeof getHeroAvatarURL==='function'?getHeroAvatarURL():null;}\n    return {kind,sprite,name:window.CHAOS_ONLINE?.nick||'Você',level:p.lvl||1};\n  }\n"
  ],
  [
    "    o.txt.x = o.sp.x; o.txt.y = o.sp.y - 46;",
    "    o.txt.x = o.sp.x; o.txt.y = o.sp.y - o.sp.displayHeight * 0.75;"
  ]
];

function patchMovementSprites(html) {
  for (const [before, after] of replacements) {
    const index = html.indexOf(before);
    if (index < 0 || html.indexOf(before, index + before.length) >= 0) {
      throw new Error('Sprite renderer anchor missing or duplicated: ' + before.slice(0, 90));
    }
    html = html.slice(0, index) + after + html.slice(index + before.length);
  }
  return html;
}
module.exports = { patchMovementSprites };
